// Package catalog is Likha's bundled model metadata (specs/model-metadata):
// context limits and prices in US dollars per million tokens for each
// (provider, model) pair Likha's predefined providers serve, with the
// provenance of every row. models.json is generated by ./gen from the
// models.dev catalog plus the hand-checked overrides.json and embedded at
// build time; never edit models.json by hand. Lookups match the exact pair:
// no prefix matching and no borrowing from another provider.
package catalog

//go:generate go run ./gen

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strings"
	"sync"
)

//go:embed models.json
var embedded []byte

// Schema is the models.json format version this package reads.
const Schema = 1

// SourceUpstream and SourceOverride name where a row's values came from.
const (
	SourceUpstream = "models.dev"
	SourceOverride = "override"
)

// BillingSubscription marks a provider using plan allowance rather than API
// token prices. It does not establish a zero charge: account-side credits may
// be separately enabled, and charges are known only when reported.
const BillingSubscription = "subscription"

// File is the whole catalog.
type File struct {
	Schema    int                 `json:"schema"`
	Generated string              `json:"generated"` // YYYY-MM-DD of the last change
	Upstream  Upstream            `json:"upstream"`
	Providers map[string]Provider `json:"providers"` // keyed by Likha canonical provider name
}

// Upstream names the catalog the file was generated from.
type Upstream struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// Provider is one Likha provider's models.
type Provider struct {
	Upstream string           `json:"upstream,omitempty"` // upstream provider ID; "" = curated only
	Billing  string           `json:"billing,omitempty"`  // BillingSubscription or ""
	Models   map[string]Model `json:"models"`             // keyed by the exact API model ID
}

// Model is one model's metadata. Zero limits mean unknown; a nil Cost means
// unknown pricing.
type Model struct {
	Name       string   `json:"name,omitempty"`
	Context    int64    `json:"context,omitempty"` // context window in tokens
	Input      int64    `json:"input,omitempty"`   // max prompt tokens, only when below Context
	Output     int64    `json:"output,omitempty"`  // max output tokens
	Cost       *Cost    `json:"cost,omitempty"`
	Reasoning  bool     `json:"reasoning,omitempty"`
	Modalities []string `json:"modalities,omitempty"` // input modalities
	Status     string   `json:"status,omitempty"`     // upstream status, e.g. "deprecated"
	Updated    string   `json:"updated,omitempty"`    // upstream last_updated
	Source     string   `json:"source"`               // SourceUpstream or SourceOverride
	Ref        string   `json:"ref,omitempty"`        // overrides: doc URL or repo path
	Verified   string   `json:"verified,omitempty"`   // overrides: YYYY-MM-DD
	Note       string   `json:"note,omitempty"`
	// Overridden lists the fields an override replaced on a models.dev
	// row; Ref and Verified vouch only for these, the rest stay upstream
	// values. Empty on an override row means the whole row is curated.
	Overridden []string `json:"overridden,omitempty"`
}

// Rates are US dollars per million tokens. A nil optional rate means no
// separate rate is known: cache tokens then price at Input, reasoning
// tokens at Output.
type Rates struct {
	Input      float64  `json:"input"`
	Output     float64  `json:"output"`
	CacheRead  *float64 `json:"cache_read,omitempty"`
	CacheWrite *float64 `json:"cache_write,omitempty"`
	Reasoning  *float64 `json:"reasoning,omitempty"`
}

// Tier replaces the base rates for a whole request whose prompt exceeds
// Above tokens.
type Tier struct {
	Above int64 `json:"above"`
	Rates
}

// Cost is a model's price card: base rates plus context tiers, sorted by
// Above ascending.
type Cost struct {
	Rates
	Tiers []Tier `json:"tiers,omitempty"`
}

// RatesFor returns the rates that apply to a request with promptTokens: the
// highest tier the prompt exceeds, else the base rates.
func (c Cost) RatesFor(promptTokens int64) Rates {
	rates := c.Rates
	for _, tier := range c.Tiers {
		if promptTokens > tier.Above {
			rates = tier.Rates
		}
	}
	return rates
}

// PromptLimit is the model's prompt budget: the input limit when one is
// known, else the context window; 0 means unknown.
func (m Model) PromptLimit() int64 {
	if m.Input > 0 {
		return m.Input
	}
	return m.Context
}

var (
	loadOnce sync.Once
	loaded   *File
	loadErr  error
)

// Default returns the embedded catalog, parsed and validated once.
func Default() (*File, error) {
	loadOnce.Do(func() {
		loaded, loadErr = Parse(embedded)
	})
	return loaded, loadErr
}

// Parse decodes and validates a catalog file.
func Parse(data []byte) (*File, error) {
	var f File
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("model catalog: %w", err)
	}
	if err := Validate(&f); err != nil {
		return nil, err
	}
	return &f, nil
}

// Lookup returns the embedded catalog row for the exact provider and model
// pair. ok is false for an unknown pair or an unreadable catalog.
func Lookup(provider, model string) (Model, bool) {
	f, err := Default()
	if err != nil {
		return Model{}, false
	}
	return f.Lookup(provider, model)
}

// Lookup returns the row for the exact provider and model pair; IDs are
// compared after trimming surrounding whitespace.
func (f *File) Lookup(provider, model string) (Model, bool) {
	p, ok := f.Providers[strings.TrimSpace(provider)]
	if !ok {
		return Model{}, false
	}
	m, ok := p.Models[strings.TrimSpace(model)]
	return m, ok
}

// Billing returns the embedded catalog's billing mode for provider.
func Billing(provider string) string {
	f, err := Default()
	if err != nil {
		return ""
	}
	return f.Providers[strings.TrimSpace(provider)].Billing
}

// Validate checks the invariants every catalog must hold: the schema
// version, provenance on every row, and finite non-negative numbers with
// ascending tiers.
func Validate(f *File) error {
	if f.Schema != Schema {
		return fmt.Errorf("model catalog: schema %d, want %d", f.Schema, Schema)
	}
	for _, providerID := range sortedKeys(f.Providers) {
		p := f.Providers[providerID]
		if p.Billing != "" && p.Billing != BillingSubscription {
			return fmt.Errorf("model catalog: %s: unknown billing %q", providerID, p.Billing)
		}
		for _, modelID := range sortedKeys(p.Models) {
			if err := validateModel(p.Models[modelID]); err != nil {
				return fmt.Errorf("model catalog: %s/%s: %w", providerID, modelID, err)
			}
		}
	}
	return nil
}

func validateModel(m Model) error {
	switch m.Source {
	case SourceUpstream:
	case SourceOverride:
		if m.Ref == "" || m.Verified == "" {
			return fmt.Errorf("override row needs ref and verified")
		}
	default:
		return fmt.Errorf("unknown source %q", m.Source)
	}
	if len(m.Overridden) > 0 && m.Source != SourceOverride {
		return fmt.Errorf("overridden fields on a non-override row")
	}
	if m.Context < 0 || m.Input < 0 || m.Output < 0 {
		return fmt.Errorf("negative limit")
	}
	if m.Cost == nil {
		return nil
	}
	if err := validateRates(m.Cost.Rates); err != nil {
		return err
	}
	last := int64(0)
	for _, tier := range m.Cost.Tiers {
		if tier.Above <= last {
			return fmt.Errorf("tiers must have ascending positive thresholds")
		}
		last = tier.Above
		if err := validateRates(tier.Rates); err != nil {
			return err
		}
	}
	return nil
}

func validateRates(r Rates) error {
	for _, v := range []*float64{&r.Input, &r.Output, r.CacheRead, r.CacheWrite, r.Reasoning} {
		if v != nil && (math.IsNaN(*v) || math.IsInf(*v, 0) || *v < 0) {
			return fmt.Errorf("price must be a finite non-negative number")
		}
	}
	return nil
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
